### ISSUE TITLE
`hanami new` generates incorrect layout, crashing on helpers call

### ISSUE THREAD

**Issue by swilgosz** [hanami/cli#120]
### Background

Version: v2.1.0-rc1

When you try to generate a new app using hanami/cli, application will crash due to the incorrect helper names in the layout .

### Steps to reproduce

```ruby
gem install hanami --pre
hanami new sandbox && cd sandbox
hanami g slice main
hanami g action home.show --slice="Main"
bundle exec hanami server
# visit localhost:2300/main/home/1
```

Application crashes due to `favicon`, `css` and `js` methods in the `layouts/app.html.erb` not being found

<img width="1518" alt="image" src="https://github.com/hanami/cli/assets/8088317/78a5638f-05c3-4ea2-9dd5-4fb228a683b2">

**Comment by olivierlacan** [comment]
Ran into this too. @timriley, here's my overdue contribution so you can un-assign 🤗
