### ISSUE TITLE
What happened to General purpose Command Line Interface framework?

### ISSUE THREAD

**Issue by jglauche** [hanami/cli#15]
Hi,

I've got hanami-cli 0.3.1 as dependency in a project. It breaks on ruby 3.0 and was looking for a new version. But the new alpha versions seem to have a completely different API. 

The link in the 0.3.1 gemfile points to this repository but I cannot find the old code anywhere. It looks like this one is very specific to the hanami framework instead? Does "General purpose Command Line Interface framework" still exists under a new name?

**Comment by jodosha** [comment]
@jglauche What you're looking for it's now named `dry-cli`.
