### ISSUE TITLE
Add `--skip-route` option to `generate action` command

### ISSUE THREAD

**Issue by timriley** [hanami/cli#196]
If this is given, generating an action wouldn't attempt to update the routes file to match.

We could use this as part of our getting started guide to avoid an unnecessary line being added to the routes (which is a potential distraction for someone trying out hanami for the first time):

```
bundle exec hanami generate action home.show --skip-view --skip-routes
```

**Comment by kyleplump** [comment]
@timriley would this apply to slices as well?
