### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by mmc1ntyre** [hanami/cli#20]
The installation instructions should specify that you need the version number.  Currently, if you follow the instructions it's installing v 0.0.0.  Or rubygems needs to be fixed so that it picks up the latest version.

**Comment by jordanandree** [comment]
Ran into this same issue and was totally confused when my code was dropping these errors:
```ruby
NameError: uninitialized constant Hanami::CLI
```

setting this in my Gemfile seemed to fix the issue:

```ruby
gem 'hanami-cli', '~> 0.1.0'
```

**Comment by jodosha** [comment]
@mmc1ntyre @jordanandree Sorry folks about the confusion.

I'm not gonna fix this because in a few days we'll release `hanami-cli` `v0.1.0`.
That means `gem install hanami-cli` will install for you the version with the actual features.
