### ISSUE TITLE
App CLI commands should accept `--env`/`-e` option to set the HANAMI_ENV

### ISSUE THREAD

**Issue by timriley** [hanami/cli#214]
This:

```
hanami blah -e test
```

Feels a lot nicer than this:

```
HANAMI_ENV=test hanami blah
```

Let's make it so.

**Comment by solnic** [comment]
I actually thought we already had that 😅

**Comment by timriley** [comment]
@solnic so did I! I tried it and was surprised to discover it wasn't there. Maybe back in snowpack?

**Comment by solnic** [comment]
@timriley yeah most likely :)
