### ISSUE TITLE
Generating files over existing file behaves poorly

### ISSUE THREAD

**Issue by cllns** [hanami/cli#22]
Going to illustrate this example with `hanami/hanami`. It's an issue with this project though, not that one.

If you run: `bundle exec hanami generate action web books#index`, files are generated.

Let's say you edit `apps/web/controllers/books/index.rb` to look like this:
```ruby
module Web::Controllers::Books
  class Index
    include Web::Action

    def call(params)
      # do some stuff
      # like process params
      # create some records maybe?
      # return status codes
      # maybe serialize a hash into JSON?
      # doesn't really matter.
      # These comments are just here for length, to show the odd behavior
    end
  end
end
```

Then run `bundle exec hanami generate action web books#index` again, here's what it does to that file:

```ruby
module Web::Controllers::Books
  class Index
    include Web::Action

    def call(params)
    end
  end
end
uff
      # like process params
      # create some records maybe?
      # return status codes
      # maybe serialize a hash into JSON?
      # doesn't really matter.
      # These comments are just here for length, to show the odd behavior
    end
  end
end
```
(Yes, I pasted that correctly. The output is very strange, and not correct Ruby)

Instead we should ask the user if they want to replace or skip any existing files. And, if they replace, we obviously want to do it properly, by deleting the file first.

**Comment by AlfonsoUceda** [comment]
@cllns This is not related to this gem, this is related how we handle files in hanami CLI. I'm going ot move it.

**Comment by AlfonsoUceda** [comment]
Closing in favor of https://github.com/hanami/hanami/issues/855
