### ISSUE TITLE
Default Arguments are not propagated

### ISSUE THREAD

**Issue by cblackburn-ajla** [hanami/cli#23]
Steps to reproduce:

* Specify default argument(s) in the `Command` code:

```
      argument(
        :output_file,
        default: DEFAULT_HTML_FILE,
        desc: "Specify HTML output file. Defaults to #{DEFAULT_HTML_FILE}"
      )
```

* Specify an option:

```
      option(
        :sort_order,
        aliases: ['-s'],
        type: :string,
        values: %w[alpha date],
        default: 'alpha',
        desc: 'Sorty by name-alpha (ascending), or date of last commit (descending)'
      )
```

Help output

```
➤ exe/codemonkey dig ../ -h
Command:
  codemonkey dig

Usage:
  codemonkey dig [OUTPUT_FILE]

Arguments:
  OUTPUT_FILE         	# Specify HTML output file. Defaults to 'git_repos.hml'

Options:
  --sort-order=VALUE, -s VALUE    	# Sort by name-alpha (ascending), or date of last commit (descending)
  --help, -h                      	# Print this help
```

* Then run the command as follows:

```
codemonkey dig --sort-order=date
```

It will then assume the `OUTPUT_FILE` is `--sort-order=date` and create a file with that name.

**Comment by cblackburn-ajla** [comment]
Let me know if I can help or if you need more info. I started to analyze and create a PR but paying jobs cut my time short. I may have some time this weekend.

**Comment by AlfonsoUceda** [comment]
there's no hurry @cblackburn-ajla but it would be helpful if you want to contribute ;)

**Comment by cllns** [comment]
Seems very similar to #21 (same issue, except there's no DEFAULT value for that one, it should just return an error instead)

**Comment by jodosha** [comment]
Fixed by https://github.com/hanami/cli/pull/24
