### ISSUE TITLE
Variadic Arguments

### ISSUE THREAD

**Issue by whoward** [hanami/cli#26]
Hello,
Firstly thanks for Hanami CLI! It is so much more elegant than Thor, which has been my goto tool up to this point.

On to business, I'm in the process of porting an old Thor based CLI to Hanami CLI and I found a dealbreaker missing feature for me - being able to parse and use a variable number of arguments to the CLI.  

The use case here is something similar to `ssh`, `docker run`, and the like where the user provides a series of arguments that'll become the command our program will execute somewhere.

Example:
```bash
ssh root@192.168.0.1 -- /bin/bash -c "echo '127.0.0.1 myapp.com' > /etc/hosts"
```
```bash
docker run -it --rm postgres:latest /bin/bash
```
```bash
docker run -it --rm postgres:latest -- psql postgres://user:pass@myhost/mydb -c "select * from users"
```

As you can see they can get pretty elaborate ;)

I've kind of hacked it in this way - but I'd rather make it official and do it more elegantly:

```patch
diff --git a/lib/hanami/cli/parser.rb b/lib/hanami/cli/parser.rb
index e9b7534..2cc18b1 100644
--- a/lib/hanami/cli/parser.rb
+++ b/lib/hanami/cli/parser.rb
@@ -27,6 +27,8 @@ module Hanami
           end
         end.parse!(arguments)

+        Hanami::CLI.define_singleton_method(:all_arguments) { arguments }
+
         parsed_options = command.default_params.merge(parsed_options)
         parse_required_params(command, arguments, names, parsed_options)
       rescue ::OptionParser::ParseError
```

I'm happy to do the work on it but figured I'd ask first as to how it should be done - any opinions?

**Comment by billdueber** [comment]
Struggling with this same problem right now -- being able to pass, say, a set of filenames is crucial to an awful lot of things. 

Right now, I'm futzing with ARGV directly and hoping for the best. Having it built in would be awesome.

**Comment by cllns** [comment]
Thanks for your input folks! 

@AlfonsoUceda @jodosha what do you think?

**Comment by AlfonsoUceda** [comment]
@whoward thanks for this issue, please open a PR adding this feature please ;)

**Comment by whoward** [comment]
Sorry for the long delay - I have submitted a PR that should cover this issue.
