### ISSUE TITLE
Need more informative error messages

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [hanami/cli#32]
i try:
```
hanami new laanz-backend --database=postgresql --test=rspec --aplication-name=api
```

And got error, that contains absolutely uninformative message:
```
Error: Invalid param provided
```

Not problem, i can find error, but can it be more informative?

**Comment by jodosha** [comment]
@dmitry-vakhnenko hi, mr @davydovanton will take care of it.

@davydovanton Please target `master` branch for this. Thank you.

**Comment by davydovanton** [comment]
done, could you check it, folks?
cc @hanami/core

**Comment by davydovanton** [comment]
@dmitry-vakhnenko hey, I merged my PR, that's why I'll close this issue. If you have any suggestions or ideas - feel free to ping me or any other hanami core (or create a issue). Thanks for you issue! <3
