### ISSUE TITLE
Typo in UnkwnownCommandError class name

### ISSUE THREAD

**Issue by d4rky-pl** [hanami/cli#35]
Class should be named `UnknownCommandError` instead

**Comment by cllns** [comment]
Oops, thanks! Would be a great first PR for anyone to grab :)

Was introduced in this PR: https://github.com/hanami/cli/pull/28/files

**Comment by d4rky-pl** [comment]
Question is: should the typo version be aliased/kept for backwards compatibility? (`UnknownCommandError < UnkwnownCommandError` so `rescue UnkwnownCommandError` still works)

**Comment by cllns** [comment]
@d4rky-pl Yea, and we can deprecate the misspelled name with [`Hanami::Utils::Deprecation`](https://www.rubydoc.info/gems/hanami-utils/Hanami/Utils/Deprecation). By checking something like `if self.class.name == "UnkwnownCommandError"`, I think.

**Comment by davydovanton** [comment]
I think we can close this issue. @d4rky-pl thank you for your work and contribution to CLI 👏
