### ISSUE TITLE
Can't figure out how to pass default values during #register

### ISSUE THREAD

**Issue by billdueber** [hanami/cli#44]
Looking at the code it *seems* like you can pass already-filled-in options to #register, but man, I can't for the life of me figure out what's going on with that.  I had thought I could do:

```ruby
MyCLI.register 'staging deploy', MedInstaller::Remote::Deploy, target: "staging"
```

...and get an option named 'target'. But no combination of `register` syntax and `argument` or `option` declarations in the target class is giving me anything useful. Any help appreciated.

**Comment by AlfonsoUceda** [comment]
Hi @billdueber, you can't pass default values in register DSL, just aliases for the command. Inside commands class, you can pass default values for `argument`s and `option`s dsls, an example:
```ruby
class Rollback < Hanami::CLI::Command
  desc "Rollback the database"

  argument :steps, desc: "Number of versions to rollback", default: 1

  def call(steps:, **)
    puts steps
  end
end
```
