### ISSUE TITLE
Is it possible to have multi-level subcommands?

### ISSUE THREAD

**Issue by kigster** [hanami/cli#55]
I saw the example in the README, where a command is registered as two separate words: `generate configuration` — see below:

```ruby
#!/usr/bin/env ruby
require "bundler/setup"
require "hanami/cli"

module Foo
  module CLI
    module Commands
      extend Hanami::CLI::Registry

      module Generate
        class Configuration < Hanami::CLI::Command
          def call(*)
          end
        end

        class Project < Hanami::CLI::Command
          def call(*)
          end
        end
      end
    end
  end
end

Foo::CLI::Commands.register "generate configuration", Foo::CLI::Commands::Generate::Configuration
Foo::CLI::Commands.register "generate project", Foo::CLI::Commands::Generate::Project

Hanami::CLI.new(Foo::CLI::Commands).call
```
However, when run with --help, this produces:

```
Commands:
  hanami-test generate [SUBCOMMAND]
```

The word `configuration` becomes a "subcommand", and is only visible if I run `cli generate --help`

```
Commands:
  cli generate configuration
  cli generate project
```

I would love to be able to see all options in a global help message. For instance:

```
 cli generate configuration NAME  
 cli generate project NAME
 cli build project NAME
 cli deploy project NAME
 cli deploy static NAME
```

Alternatively (albeit this does not work if arguments to the commands are different)

```
 cli generate [ configuration NAME | project NAME ]
 cli build project NAME
 cli deploy [ project NAME | static NAME ]
```

Is it possible? 

Is it desirable?

**Comment by kigster** [comment]
Never mind, of course it’s possible. 

The only somewhat non ideal thing is that it could be nice to have an automatic `—longhelp` command that would dump all commands and their subcomands as well.

**Comment by jodosha** [comment]
@kigster It's possible to achieve. Please have a look at https://github.com/hanami/hanami/blob/master/lib/hanami/cli/commands.rb

**Comment by unrooty** [comment]
@kigster Hello! Your example provides multilevel subcommands implementation. But what about dump all commands and their subcomands as well? Is there any way to reach this? Hanami CLI only have output without subcommands sadly :disappointed: 

![Screenshot from 2020-01-31 09-08-45](https://user-images.githubusercontent.com/26375494/73516399-5504e500-4409-11ea-85cb-12fe969691f1.png)
