### ISSUE TITLE
No warning for `hanami new` when the directory already exists

### ISSUE THREAD

**Issue by janko** [hanami/cli#59]
I ran `hanami new blog`, but didn't realize the current working directory already had a `blog/` directory, where I had previously generated a Rails application. The generator happily merged Hanami files into the Rails codebase. It would be great if the `hanami new` command would abort if the target directory already exists 🙂

**Comment by janko** [comment]
Sorry, this appears to be a duplicate of https://github.com/hanami/cli/issues/52 😛

**Comment by jodosha** [comment]
@janko Fixed in https://github.com/hanami/cli/pull/66
