### ISSUE TITLE
`hanami g action` overrides existing action + spec

### ISSUE THREAD

**Issue by radar** [hanami/cli#67]
## What I tried to do:

```
hanami g action accounts.show
```

## What I expected to happen:

It would not override the existing files matching those paths (`app/actions/accounts/show.rb` / `spec/actions/accounts/show_spec.rb`)

## What actually happened:

It overrode those files without asking.

**Comment by jodosha** [comment]
@radar We're aware of this. It isn't a bug, it's just we didn't implement it yet.

**Comment by cllns** [comment]
Thanks for reporting this, I plan on fixing it soon. Closing this in favor of #181 since it affects all our generators, not just action.
